[tool.ruff]
line-length = 88
target-version = "py310"
extend-exclude = ["backups", "router/logs"]

[tool.pytest.ini_options]
addopts = "-q"

[tool.mypy]
exclude = "backups|garvis_validate.py"

[tool.black]
line-length = 88
target-version = ["py310"]
extend-exclude = "backups|router/logs"
